PREFIX : <http://snomed.info/sct/900000000000207008#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX snomed: <http://snomed.info/id/>
PREFIX sphn: <https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdr-schema#>

PREFIX sph: <https://biomedit.ch/rdf/sphn-schema/sph#>
#PREFIX ns1: <https://biomedit.ch/rdf/sphn-schema/sphn#>
SELECT *
from <http://spac_insel>

WHERE {
	?lungFunction a sph:LungFunctionTestProcedure .
optional {?lungFunction sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?SubjectPseudoIdentifier.}
optional {?lungFunction sphn:hasAdministrativeCase/sphn:hasIdentifier ?SubjectPseudoIdentifier.}
optional {?lungFunction sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider.}
optional {?lungFunction sph:hasSubjectAdministrativeSex/sphn:hasCode/rdf:type/skos:prefLabel ?Sex
FILTER(LANG(?Sex) = "en" || LANG(?Sex) = "en-US").}
optional {?lungFunction sph:hasSubjectEthnicalAdjustmentParameter/sph:hasType ?Ethnicity.}
optional {?lungFunction sphn:hasSubjectAge/sphn:hasQuantity/sphn:hasValue ?Age.
?lungFunction sphn:hasSubjectAge/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/rdf:type ?Age_unit.}
optional {?lungFunction sph:hasSubjectBodyHeight/sphn:hasQuantity/sphn:hasValue ?Height_val.
?lungFunction sph:hasSubjectBodyHeight/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/rdf:type?Height_unit.}
optional {?lungFunction sph:hasSubjectBodyWeight/sphn:hasQuantity/sphn:hasValue ?Weight_val.
?lungFunction sph:hasSubjectBodyWeight/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/rdf:type?Weight_unit.}
optional {?lungFunction sph:hasSubjectBodyWeight/sphn:hasQuantity/sphn:hasValue ?Weight_val.}
optional {?lungFunction sphn:hasStartDateTime ?StartDateTime}
optional {?lungFunction sphn:hasEndDateTime ?EndDateTime}
optional {?lungFunction sphn:hasCode/rdf:type/skos:prefLabel ?LuFu_test
FILTER(LANG(?LuFu_test) = "en" || LANG(?LuFu_test) = "en-US").}
optional {?lungFunction sph:hasSession ?Session.
		optional {?Session sph:hasNumber ?Session_number. }
		optional {?Session sph:hasIntervention/sphn:hasDrug/sphn:has Article/sphn:hsName ?LuFu_intervention_drug.}
		optional {?Session sph:hasMeasurement ?Measurement.
					optional {?Measurment sph:hasNumber ?Measurement_number .}
					optional {?Measurement sph:hasMedicalDevice/sph:hasType ?Measurement_medicalDevice .}
					optional {?Measurement sph:hasResult ?Result.
							optional {?Result rdf:type ?LuFu_parameter.
										FILTER(?LuFu_parameter = sph:ForcedExpiredVolume1Second)}
							optional {?Result sphn:hasQuantity/sphn:hasValue ?LuFu_parameter_val.
										?Result sphn:hasQuantiy/sphn:hasUnit/sphn:hasCode/rdf:type ?LuFu_paramter_unit.}
							optional {?Result sph:hasEsimtationTechniqueCode/rdf:type/skos:prefLabel ?LuFu_parameter_technique.
										FILTER(LANG(?LuFu_parameter_technique) = "en" || LANG(?LuFu_parameter_technique) = "en-US").}
							}
					}
		}
}
