PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX snomed: <http://snomed.info/id/>
PREFIX sphn: <https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?AdministrativeSex ?SubjectPseudoIdentifier_Identifier ?DataProvider_InstitutionCode_Name ?Code
WHERE {
    	?AdministrativeSex a sphn:AdministrativeSex .
    	optional { ?AdministrativeSex sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?SubjectPseudoIdentifier_Identifier . }
    	optional { ?AdministrativeSex sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider_InstitutionCode_Name }
        optional { ?AdministrativeSex sphn:hasCode/rdf:type ?Code_Type .
        			optional { ?Code_Type skos:prefLabel ?Code_german .
        						FILTER(LANG(?Code_german) = "de")}
        			optional { ?Code_Type skos:prefLabel ?Code_english .
            					FILTER(LANG(?Code_english) = "en")}
        			optional { ?Code_Type skos:prefLabel ?Code_englishUS .
        						FILTER(LANG(?Code_englishUS) = "en-US")}
        			optional { ?Code_Type skos:prefLabel ?Code_englishUK .
        						FILTER(LANG(?Code_englishUK) = "en-UK")}
        			optional { ?Code_Type skos:prefLabel ?Code_french .
        						FILTER(LANG(?Code_french) = "fr")}
        			optional { ?Code_Type skos:prefLabel ?Code_frenchCH .
                				FILTER(LANG(?Code_frenchCH) = "fr-CH")}
    	BIND(COALESCE(?Code_german, ?Code_english, ?Code_englishUS, ?Code_englishUK, ?Code_french, ?Code_frenchCH) AS ?Code)}
}