PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX snomed: <http://snomed.info/id/>
PREFIX sphn: <https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?AdministrativeCase ?Identifier ?SubjectPseudoIdentifier_Identifier ?DataProvider_InstitutionCode_Name ?CareHandling ?AdmissionDateTime ?DischargeDateTime
WHERE {
    ?AdministrativeCase a sphn:AdministrativeCase .
    OPTIONAL { ?AdministrativeCase sphn:hasIdentifier ?Identifier . }
    OPTIONAL { ?AdministrativeCase sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?SubjectPseudoIdentifier_Identifier . }
    OPTIONAL { ?AdministrativeCase sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider_InstitutionCode_Name . }
    OPTIONAL { ?AdministrativeCase sphn:hasCareHandling/sphn:hasTypeCode/rdf:type ?CareHandling_Type .
        		OPTIONAL { ?CareHandling_Type skos:prefLabel ?CareHandling_german .
        					FILTER(LANG(?CareHandling_german) = "de")}
       		 	OPTIONAL { ?CareHandling_Type skos:prefLabel ?CareHandling_english .
        					FILTER(LANG(?CareHandling_english) = "en")}
        		OPTIONAL { ?CareHandling_Type skos:prefLabel ?CareHandling_englishUS .
        					FILTER(LANG(?CareHandling_englishUS) = "en-US")}
       		 	OPTIONAL { ?CareHandling_Type skos:prefLabel ?CareHandling_englishUK .
        					FILTER(LANG(?CareHandling_englishUK) = "en-UK")}
        		OPTIONAL { ?CareHandling_Type skos:prefLabel ?CareHandling_french .
        					FILTER(LANG(?CareHandling_french) = "fr")}
       		 	OPTIONAL { ?CareHandling_Type skos:prefLabel ?CareHandling_frenchCH .
        					FILTER(LANG(?CareHandling_frenchCH) = "fr-CH")}
    			BIND(COALESCE(?CareHandling_german, ?CareHandling_english, ?CareHandling_englishUS, ?CareHandling_englishUK, ?CareHandling_french, ?CareHandling_frenchCH) AS ?CareHandling)}
    OPTIONAL { ?AdministrativeCase sphn:hasAdmissionDateTime ?AdmissionDateTime . }
    OPTIONAL { ?AdministrativeCase sphn:hasDischargeDateTime ?DischargeDateTime . }
}