PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX snomed: <http://snomed.info/id/>
PREFIX sphn: <https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?BilledDiagnosis ?AdministrativeCase ?AdministrativeCase_Identifier ?SubjectPseudoIdentifier_Identifier ?DataProvider_InstitutionCode_Name ?RecordDateTime ?Code ?Code_Label ?Rank
WHERE {
    	?BilledDiagnosis a sphn:BilledDiagnosis .
    	optional { ?BilledDiagnosis sphn:hasAdministrativeCase ?AdministrativeCase . 
        	optional { ?AdministrativeCase sphn:hasIdentifier ?AdministrativeCase_Identifier . }}
    	OPTIONAL { ?BilledDiagnosis sphn:hasSubjectPseudoIdentifier ?SubjectPseudoIdentifier.
       		Optional { ?SubjectPseudoIdentifier sphn:hasIdentifier ?SubjectPseudoIdentifier_Identifier . }
    		OPTIONAL { ?SubjectPseudoIdentifier sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider_InstitutionCode_Name . }}
        optional { ?BilledDiagnosis sphn:hasRecordDateTime ?RecordDateTime . }
        optional { ?BilledDiagnosis sphn:hasCode/rdf:type ?Code . 
        			optional { ?Code rdfs:label ?Code_Label_german . 
        						FILTER(LANG(?Code_Label_german) = "de")}
    				optional { ?Code rdfs:label ?Code_Label_english . 
        			FILTER(LANG(?Code_Label_english) = "en")}
    				optional { ?Code rdfs:label ?Code_Label_englishUS . 
        						FILTER(LANG(?Code_Label_englishUS) = "en-US")}
    				optional { ?Code rdfs:label ?Code_Label_englishUK . 
        						FILTER(LANG(?Code_Label_englishUK) = "en-UK")}
    				optional { ?Code rdfs:label ?Code_Label_french . 
        						FILTER(LANG(?Code_Label_french) = "fr")}
    				optional { ?Code rdfs:label ?Code_Label_frenchCH . 
        						FILTER(LANG(?Code_Label_frenchCH) = "fr-CH")}
    				BIND(COALESCE(?Code_Label_german, ?Code_Label_english, ?Code_Label_englishUS, ?Code_Label_englishUK, ?Code_Label_french, ?Code_Label_frenchCH) AS ?Code_Label)}
    	optional { ?BilledDiagnosis sphn:hasRank/rdfs:label ?Rank}
}