PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX snomed: <http://snomed.info/id/>
PREFIX sphn: <https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    	?BirthDate a sphn:BirthDate .
        optional { ?BirthDate sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?SubjectPseudoIdentifier_Identifier . }
        optional { ?BirthDate sphn:hasYear ?Year . }
        optional { ?BirthDate sphn:hasMonth ?Month . }
        optional { ?BirthDate sphn:hasDay ?Day . }
    }