PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sphn: <https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?CircumferenceMeasurement ?SubjectPseudoIdentifier_Identifier ?DataProvider_InstitutionCode_Name ?AdministrativeCase ?AdministrativeCase_Identifier ?StartDateTime ?EndDateTime ?BodySite_Code_Label ?Result_Quantity_Value ?Result_Quantity_Unit ?Result_DateTime

WHERE {
    	?CircumferenceMeasurement a sphn:CircumferenceMeasurement .
   		OPTIONAL { ?CircumferenceMeasurement sphn:hasSubjectPseudoIdentifier ?SubjectPseudoIdentifier.
       		Optional { ?SubjectPseudoIdentifier sphn:hasIdentifier ?SubjectPseudoIdentifier_Identifier . }
    		OPTIONAL { ?SubjectPseudoIdentifier sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider_InstitutionCode_Name .}}
    	optional { ?CircumferenceMeasurement sphn:hasAdministrativeCase ?AdministrativeCase . 
        	optional { ?AdministrativeCase sphn:hasIdentifier ?AdministrativeCase_Identifier . }}
        optional { ?CircumferenceMeasurement sphn:hasStartDateTime ?StartDateTime . }
    	optional { ?CircumferenceMeasurement sphn:hasEndDateTime ?EndDateTime . }
    	optional { ?CircumferenceMeasurement sphn:hasBodySite/sphn:hasCode/rdf:type ?BodySite_Code_Type .
        			optional { ?BodySite_Code_Type skos:prefLabel ?BodySite_Code_Label_german . 
    							FILTER(LANG(?BodySite_Code_Label_german) = "de" )}
        			optional { ?BodySite_Code_Type skos:prefLabel ?BodySite_Code_Label_english . 
    							FILTER(LANG(?BodySite_Code_Label_english) = "en" )}
        			optional { ?BodySite_Code_Type skos:prefLabel ?BodySite_Code_Label_englishUS . 
    							FILTER(LANG(?BodySite_Code_Label_englishUS) = "en-US" )}
        			optional { ?BodySite_Code_Type skos:prefLabel ?BodySite_Code_Label_englishUK . 
    							FILTER(LANG(?BodySite_Code_Label_englishUK) = "en-UK" )}
        			optional { ?BodySite_Code_Type skos:prefLabel ?BodySite_Code_Label_french. 
    							FILTER(LANG(?BodySite_Code_Label_french) = "fr" )}
        			optional { ?BodySite_Code_Type skos:prefLabel ?BodySite_Code_Label_frenchCH. 
    							FILTER(LANG(?BodySite_Code_Label_frenchCH) = "fr-CH" )}
        			BIND(COALESCE(?BodySite_Code_Label_german, ?BodySite_Code_Label_english, ?BodySite_Code_Label_englishUS, ?BodySite_Code_Label_englishUK, ?BodySite_Code_Label_french, ?BodySite_Code_Label_frenchCH) AS ?BodySite_Code_Label)}
    	optional { ?CircumferenceMeasurement sphn:hasResult ?Result .
        			optional { ?Result sphn:hasQuantity ?Result_Quantity .
        						optional { ?Result_Quantity sphn:hasValue ?Result_Quantity_Value. }
    							optional { ?Result_Quantity sphn:hasUnit/sphn:hasCode/rdf:type/rdfs:label ?Result_Quantity_Unit. }}
        			optional { ?Result sphn:hasDateTime ?Result_DateTime}}
}    