PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX snomed: <http://snomed.info/id/>
PREFIX sphn: <https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?Consent ?SubjectPseudoIdentifier_Identifier ?DataProvider_InstitutionCode_Name ?TypeCode_Label ?StatusCode_Label
WHERE {
    	?Consent a sphn:Consent .
    	optional { ?Consent sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?SubjectPseudoIdentifier_Identifier . }
    	optional { ?Consent sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider_InstitutionCode_Name }
    	optional { ?Consent sphn:hasTypeCode ?TypeCode .
        			optional { ?TypeCode rdf:type/skos:prefLabel ?TypeCode_german .
        						FILTER(LANG(?TypeCode_german) = "de")}
        			optional { ?TypeCode rdf:type/skos:prefLabel ?TypeCode_english .
            					FILTER(LANG(?TypeCode_english) = "en")}
        			optional { ?TypeCode rdf:type/skos:prefLabel ?TypeCode_englishUS .
        						FILTER(LANG(?TypeCode_englishUS) = "en-US")}
        			optional { ?TypeCode rdf:type/skos:prefLabel ?TypeCode_englishUK .
        						FILTER(LANG(?TypeCode_englishUK) = "en-UK")}
        			optional { ?TypeCode rdf:type/skos:prefLabel ?TypeCode_french .
        						FILTER(LANG(?TypeCode_french) = "fr")}
        			optional { ?TypeCode rdf:type/skos:prefLabel ?TypeCode_frenchCH .
                				FILTER(LANG(?TypeCode_frenchCH) = "fr-CH")}
    	BIND(COALESCE(?TypeCode_german, ?TypeCode_english, ?TypeCode_englishUS, ?TypeCode_englishUK, ?TypeCode_french, ?TypeCode_frenchCH) AS ?TypeCode_Label)}
    	optional { ?Consent sphn:hasStatusCode ?StatusCode .
        			optional { ?StatusCode rdf:type/skos:prefLabel ?StatusCode_german .
        						FILTER(LANG(?StatusCode_german) = "de")}
        			optional { ?StatusCode rdf:type/skos:prefLabel ?StatusCode_english .
            					FILTER(LANG(?StatusCode_english) = "en")}
        			optional { ?StatusCode rdf:type/skos:prefLabel ?StatusCode_englishUS .
        						FILTER(LANG(?StatusCode_englishUS) = "en-US")}
        			optional { ?StatusCode rdf:type/skos:prefLabel ?StatusCode_englishUK .
        						FILTER(LANG(?StatusCode_englishUK) = "en-UK")}
        			optional { ?StatusCode rdf:type/skos:prefLabel ?StatusCode_french .
        						FILTER(LANG(?StatusCode_french) = "fr")}
        			optional { ?StatusCode rdf:type/skos:prefLabel ?StatusCode_frenchCH .
                				FILTER(LANG(?StatusCode_frenchCH) = "fr-CH")}
    	BIND(COALESCE(?StatusCode_german, ?StatusCode_english, ?StatusCode_englishUS, ?StatusCode_englishUK, ?StatusCode_french, ?StatusCode_frenchCH) AS ?StatusCode_Label)}
}