PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX snomed: <http://snomed.info/id/>
PREFIX sphn: <https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?DrugAdministrationEvent ?SubjectPseudoIdentifier_Identifier ?AdministrativeCase_Identifier ?DataProvider_InstitutionCode_Name ?StartDateTime ?EndDateTime ?Duration_Quantity_Value ?Duration_Quantity_Unit ?TimePattern_TypeCode_Label ?AdministrationRouteCode_Label ?ReasonToStopCode_Label ?Drug_Article_Name ?Drug_ActiveIngredient_GenericName ?Drug_ActiveIngredient_GenericName_Code ?Drug_ActiveIngredient_GenericName_Code_Label ?Drug_Quantity_Value ?Drug_Quantity_Unit
WHERE {
    	?DrugAdministrationEvent a sphn:DrugAdministrationEvent .
    	optional { ?DrugAdministrationEvent sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?SubjectPseudoIdentifier_Identifier . }
        optional { ?DrugAdministrationEvent sphn:hasAdministrativeCase/sphn:hasIdentifier ?AdministrativeCase_Identifier . }
        optional { ?DrugAdministrationEvent sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider_InstitutionCode_Name . }
        optional { ?DrugAdministrationEvent sphn:hasStartDateTime ?StartDateTime . }
        optional { ?DrugAdministrationEvent sphn:hasEndDateTime ?EndDateTime . }
        optional { ?DrugAdministrationEvent sphn:hasDuration/sphn:hasQuantity ?Duration_Quantity .
        			optional { ?Duration_Quantity sphn:hasValue ?Duration_Quantity_Value . }
        			optional { ?Duration_Quantity sphn:hasUnit/sphn:hasCode/rdf:type/rdfs:label ?Duration_Quantity_Unit . }}
        optional { ?DrugAdministrationEvent sphn:hasTimePattern/sphn:hasTypeCode/rdf:type ?TimePattern_TypeCode_Type . 
        			optional { ?TimePattern_TypeCode_Type skos:prefLabel ?TimePattern_TypeCode_Label_german . 
    							FILTER(LANG(?TimePattern_TypeCode_Label_german) = "de" )}
        			optional { ?TimePattern_TypeCode_Type skos:prefLabel ?TimePattern_TypeCode_Label_english . 
    							FILTER(LANG(?TimePattern_TypeCode_Label_english) = "en" )}
        			optional { ?TimePattern_TypeCode_Type skos:prefLabel ?TimePattern_TypeCode_Label_englishUS . 
    							FILTER(LANG(?TimePattern_TypeCode_Label_englishUS) = "en-US" )}
        			optional { ?TimePattern_TypeCode_Type skos:prefLabel ?TimePattern_TypeCode_Label_englishUK . 
    							FILTER(LANG(?TimePattern_TypeCode_Label_englishUK) = "en-UK" )}
        			optional { ?TimePattern_TypeCode_Type skos:prefLabel ?TimePattern_TypeCode_Label_french. 
    							FILTER(LANG(?TimePattern_TypeCode_Label_french) = "fr" )}
        			optional { ?TimePattern_TypeCode_Type skos:prefLabel ?TimePattern_TypeCode_Label_frenchCH. 
    							FILTER(LANG(?TimePattern_TypeCode_Label_frenchCH) = "fr-CH" )}
        			BIND(COALESCE(?TimePattern_TypeCode_Label_german, ?TimePattern_TypeCode_Label_english, ?TimePattern_TypeCode_Label_englishUS, ?TimePattern_TypeCode_Label_englishUK, ?TimePattern_TypeCode_Label_french, ?TimePattern_TypeCode_Label_frenchCH) AS ?TimePattern_TypeCode_Label)}
    	optional { ?DrugAdministrationEvent sphn:hasAdministrationRouteCode/rdf:type ?AdministrationRouteCode_Type . 
    				optional { ?AdministrationRouteCode_Type skos:prefLabel ?AdministrationRouteCode_Label_german . 
    							FILTER(LANG(?AdministrationRouteCode_Label_german) = "de" )}
        			optional { ?AdministrationRouteCode_Type skos:prefLabel ?AdministrationRouteCode_Label_english . 
    							FILTER(LANG(?AdministrationRouteCode_Label_english) = "en" )}
        			optional { ?AdministrationRouteCode_Type skos:prefLabel ?AdministrationRouteCode_Label_englishUS . 
    							FILTER(LANG(?AdministrationRouteCode_Label_englishUS) = "en-US" )}
        			optional { ?AdministrationRouteCode_Type skos:prefLabel ?AdministrationRouteCode_Label_englishUK . 
    							FILTER(LANG(?AdministrationRouteCode_Label_englishUK) = "en-UK" )}
        			optional { ?AdministrationRouteCode_Type skos:prefLabel ?AdministrationRouteCode_Label_french. 
    							FILTER(LANG(?AdministrationRouteCode_Label_french) = "fr" )}
        			optional { ?AdministrationRouteCode_Type skos:prefLabel ?AdministrationRouteCode_Label_frenchCH. 
    							FILTER(LANG(?AdministrationRouteCode_Label_frenchCH) = "fr-CH" )}
        			BIND(COALESCE(?AdministrationRouteCode_Label_german, ?AdministrationRouteCode_Label_english, ?AdministrationRouteCode_Label_englishUS, ?TimePattern_TypeCode_Label_englishUK, ?AdministrationRouteCode_Label_french, ?AdministrationRouteCode_Label_frenchCH) AS ?AdministrationRouteCode_Label)}
    	optional { ?DrugAdministrationEvent sphn:hasReasonToStopCode/rdf:type ?ReasonToStopCode_Type .
        			optional { ?ReasonToStopCode_Type skos:prefLabel ?ReasonToStopCode_Label_german . 
    							FILTER(LANG(?ReasonToStopCode_Label_german) = "de" )}
        			optional { ?ReasonToStopCode_Type skos:prefLabel ?ReasonToStopCode_Label_english . 
    							FILTER(LANG(?ReasonToStopCode_Label_english) = "en" )}
        			optional { ?ReasonToStopCode_Type skos:prefLabel ?ReasonToStopCode_Label_englishUS . 
    							FILTER(LANG(?ReasonToStopCode_Label_englishUS) = "en-US" )}
        			optional { ?ReasonToStopCode_Type skos:prefLabel ?ReasonToStopCode_Label_englishUK . 
    							FILTER(LANG(?ReasonToStopCode_Label_englishUK) = "en-UK" )}
        			optional { ?ReasonToStopCode_Type skos:prefLabel ?ReasonToStopCode_Label_french. 
    							FILTER(LANG(?ReasonToStopCode_Label_french) = "fr" )}
        			optional { ?ReasonToStopCode_Type skos:prefLabel ?ReasonToStopCode_Label_frenchCH. 
    							FILTER(LANG(?ReasonToStopCode_Label_frenchCH) = "fr-CH" )}
        			BIND(COALESCE(?ReasonToStopCode_Label_german, ?ReasonToStopCode_Label_english, ?ReasonToStopCode_Label_englishUS, ?ReasonToStopCode_Label_englishUK, ?ReasonToStopCode_Label_french, ?ReasonToStopCode_Label_frenchCH) AS ?ReasonToStopCode_Label)}
        optional { ?DrugAdministrationEvent sphn:hasDrug ?Drug .
        			optional { ?Drug sphn:hasArticle/sphn:hasName ?Drug_Article_Name . }
        			optional { ?Drug sphn:hasActiveIngredient ?Drug_ActiveIngredient . 
            					optional { ?Drug_ActiveIngredient sphn:hasGenericName ?Drug_ActiveIngredient_GenericName . }
    			            	optional { ?Drug_ActiveIngredient sphn:hasCode/rdf:type ?Drug_ActiveIngredient_GenericName_Code . 
            								optional { ?Drug_ActiveIngredient_GenericName_Code rdfs:label ?Drug_ActiveIngredient_GenericName_Code_Label_german . 
    													FILTER(LANG(?Drug_ActiveIngredient_GenericName_Code_Label_german) = "de" )}
        									optional { ?Drug_ActiveIngredient_GenericName_Code rdfs:label ?Drug_ActiveIngredient_GenericName_Code_Label_english . 
    													FILTER(LANG(?Drug_ActiveIngredient_GenericName_Code_Label_english) = "en" )}
                							optional { ?Drug_ActiveIngredient_GenericName_Code rdfs:label ?Drug_ActiveIngredient_GenericName_Code_Label_englishUS . 
    													FILTER(LANG(?Drug_ActiveIngredient_GenericName_Code_Label_englishUS) = "en-US" )}
                							optional { ?Drug_ActiveIngredient_GenericName_Code rdfs:label ?Drug_ActiveIngredient_GenericName_Code_Label_englishUK . 
    													FILTER(LANG(?Drug_ActiveIngredient_GenericName_Code_Label_englishUK) = "en-UK" )}
                							optional { ?Drug_ActiveIngredient_GenericName_Code rdfs:label ?Drug_ActiveIngredient_GenericName_Code_Label_french . 
    													FILTER(LANG(?Drug_ActiveIngredient_GenericName_Code_Label_french) = "fr" )}
                							optional { ?Drug_ActiveIngredient_GenericName_Code rdfs:label ?Drug_ActiveIngredient_GenericName_Code_Label_frenchCH . 
    													FILTER(LANG(?Drug_ActiveIngredient_GenericName_Code_Label_frenchCH) = "fr-CH" )}
        									BIND(COALESCE(?Drug_ActiveIngredient_GenericName_Code_Label_german, ?Drug_ActiveIngredient_GenericName_Code_Label_english, ?Drug_ActiveIngredient_GenericName_Code_Label_englishUS, ?Drug_ActiveIngredient_GenericName_Code_Label_englishUK, ?Drug_ActiveIngredient_GenericName_Code_Label_french, ?Drug_ActiveIngredient_GenericName_Code_Label_frenchCH) AS ?Drug_ActiveIngredient_GenericName_Code_Label)}
        						}
        			optional { ?Drug sphn:hasQuantity ?Drug_Quantity .
            					optional { ?Drug_Quantity sphn:hasValue ?Drug_Quantity_Value .}
            					optional { ?Drug_Quantity sphn:hasUnit/sphn:hasCode/rdf:type/rdfs:label ?Drug_Quantity_Unit . }}
    		}
}