PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX snomed: <http://snomed.info/id/>
PREFIX sphn: <https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?HealthcareEncounter ?Identifier ?SubjectPseudoIdentifier_Identifier ?AdministrativeCase ?AdministrativeCase_Identifier ?DataProvider_InstitutionCode_Name ?OriginLocation_TypeCode_Label ?OriginLocation_Exact ?CurrentLocation_TypeCode_Label ?CurrentLocation_Exact ?TargetLocation_TypeCode_Label ?TargetLocation_Exact ?StartDateTime ?EndDateTime ?TherapeuticArea_SpecialtyName_Label
WHERE {
	?HealthcareEncounter a sphn:HealthcareEncounter .
  
	OPTIONAL { ?HealthcareEncounter sphn:hasIdentifier ?Identifier . }
	OPTIONAL { ?HealthcareEncounter sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?SubjectPseudoIdentifier_Identifier . }
	OPTIONAL { ?HealthcareEncounter sphn:hasAdministrativeCase ?AdministrativeCase .
		OPTIONAL { ?AdministrativeCase sphn:hasIdentifier ?AdministrativeCase_Identifier . }}
	OPTIONAL { ?HealthcareEncounter sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider_InstitutionCode_Name .} 
	OPTIONAL { ?HealthcareEncounter sphn:hasOriginLocation ?OriginLocation .
		OPTIONAL { ?OriginLocation sphn:hasExact ?OriginLocation_Exact . }
		OPTIONAL { ?OriginLocation sphn:hasTypeCode/rdf:type ?OriginLocation_TypeCode .
				OPTIONAL { ?OriginLocation_TypeCode skos:prefLabel ?OriginLocation_TypeCode_Label_german . FILTER(LANG(?OriginLocation_TypeCode_Label_german) = "de") }
				OPTIONAL { ?OriginLocation_TypeCode skos:prefLabel ?OriginLocation_TypeCode_Label_germanCH . FILTER(LANG(?OriginLocation_TypeCode_Label_germanCH) = "de-CH") }
				OPTIONAL { ?OriginLocation_TypeCode skos:prefLabel ?OriginLocation_TypeCode_Label_english . FILTER(LANG(?OriginLocation_TypeCode_Label_english) = "en") }
				OPTIONAL { ?OriginLocation_TypeCode skos:prefLabel ?OriginLocation_TypeCode_Label_englishUS . FILTER(LANG(?OriginLocation_TypeCode_Label_englishUS) = "en-US") }
				OPTIONAL { ?OriginLocation_TypeCode skos:prefLabel ?OriginLocation_TypeCode_Label_englishUK . FILTER(LANG(?OriginLocation_TypeCode_Label_englishUK) = "en-UK") }
				OPTIONAL { ?OriginLocation_TypeCode skos:prefLabel ?OriginLocation_TypeCode_Label_french . FILTER(LANG(?OriginLocation_TypeCode_Label_french) = "fr") }
				BIND(COALESCE(?OriginLocation_TypeCode_Label_german,
						?OriginLocation_TypeCode_Label_germanCH,
						?OriginLocation_TypeCode_Label_english,
						?OriginLocation_TypeCode_Label_englishUS,
						?OriginLocation_TypeCode_Label_englishUK,
						?OriginLocation_TypeCode_Label_french) AS ?OriginLocation_TypeCode_Label)
		}
	}
	OPTIONAL { ?HealthcareEncounter sphn:hasCurrentLocation ?CurrentLocation .
		OPTIONAL { ?CurrentLocation sphn:hasExact ?CurrentLocation_Exact . }
		OPTIONAL { ?CurrentLocation sphn:hasTypeCode/rdf:type ?CurrentLocation_TypeCode .
				OPTIONAL { ?CurrentLocation_TypeCode skos:prefLabel ?CurrentLocation_TypeCode_Label_german . FILTER(LANG(?CurrentLocation_TypeCode_Label_german) = "de") }
				OPTIONAL { ?CurrentLocation_TypeCode skos:prefLabel ?CurrentLocation_TypeCode_Label_germanCH . FILTER(LANG(?CurrentLocation_TypeCode_Label_germanCH) = "de-CH") }
				OPTIONAL { ?CurrentLocation_TypeCode skos:prefLabel ?CurrentLocation_TypeCode_Label_english . FILTER(LANG(?CurrentLocation_TypeCode_Label_english) = "en") }
				OPTIONAL { ?CurrentLocation_TypeCode skos:prefLabel ?CurrentLocation_TypeCode_Label_englishUS . FILTER(LANG(?CurrentLocation_TypeCode_Label_englishUS) = "en-US") }
				OPTIONAL { ?CurrentLocation_TypeCode skos:prefLabel ?CurrentLocation_TypeCode_Label_englishUK . FILTER(LANG(?CurrentLocation_TypeCode_Label_englishUK) = "en-UK") }
				OPTIONAL { ?CurrentLocation_TypeCode skos:prefLabel ?CurrentLocation_TypeCode_Label_french . FILTER(LANG(?CurrentLocation_TypeCode_Label_french) = "fr") }
				BIND(COALESCE(?CurrentLocation_TypeCode_Label_german,
						?CurrentLocation_TypeCode_Label_germanCH,
						?CurrentLocation_TypeCode_Label_english,
						?CurrentLocation_TypeCode_Label_englishUS,
						?CurrentLocation_TypeCode_Label_englishUK,
						?CurrentLocation_TypeCode_Label_french) AS ?CurrentLocation_TypeCode_Label)
		}
	}
	OPTIONAL { ?HealthcareEncounter sphn:hasTargetLocation ?TargetLocation .
		OPTIONAL { ?TargetLocation sphn:hasExact ?TargetLocation_Exact . }
		OPTIONAL { ?TargetLocation sphn:hasTypeCode/rdf:type ?TargetLocation_TypeCode .
				OPTIONAL { ?TargetLocation_TypeCode skos:prefLabel ?TargetLocation_TypeCode_Label_german . FILTER(LANG(?TargetLocation_TypeCode_Label_german) = "de") }
				OPTIONAL { ?TargetLocation_TypeCode skos:prefLabel ?TargetLocation_TypeCode_Label_germanCH . FILTER(LANG(?TargetLocation_TypeCode_Label_germanCH) = "de-CH") }
				OPTIONAL { ?TargetLocation_TypeCode skos:prefLabel ?TargetLocation_TypeCode_Label_english . FILTER(LANG(?TargetLocation_TypeCode_Label_english) = "en") }
				OPTIONAL { ?TargetLocation_TypeCode skos:prefLabel ?TargetLocation_TypeCode_Label_englishUS . FILTER(LANG(?TargetLocation_TypeCode_Label_englishUS) = "en-US") }
				OPTIONAL { ?TargetLocation_TypeCode skos:prefLabel ?TargetLocation_TypeCode_Label_englishUK . FILTER(LANG(?TargetLocation_TypeCode_Label_englishUK) = "en-UK") }
				OPTIONAL { ?TargetLocation_TypeCode skos:prefLabel ?TargetLocation_TypeCode_Label_french . FILTER(LANG(?TargetLocation_TypeCode_Label_french) = "fr") }
				BIND(COALESCE(?TargetLocation_TypeCode_Label_german,
						?TargetLocation_TypeCode_Label_germanCH,
						?TargetLocation_TypeCode_Label_english,
						?TargetLocation_TypeCode_Label_englishUS,
						?TargetLocation_TypeCode_Label_englishUK,
						?TargetLocation_TypeCode_Label_french) AS ?TargetLocation_TypeCode_Label)
		}
	}
	optional { ?HealthcareEncounter sphn:hasStartDateTime ?StartDateTime . }
    optional { ?HealthcareEncounter sphn:hasEndDateTime ?EndDateTime . }
    optional { ?HealthcareEncounter sphn:hasTherapeuticArea/sphn:hasSpecialtyName ?TherapeuticArea_SpecialtyName .
		optional { ?TherapeuticArea_SpecialtyName rdfs:label ?TherapeuticArea_SpecialtyName_Label . }
    }
}